version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file: ./env/mysql.env

  rabbitmq:
    image: rabbitmq:alpine

  app-python:
    build:
      context: .
      dockerfile: Dockerfile-python
    image: app-python
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    env_file: ./env/python.env

  app-node:
    build:
      context: .
      dockerfile: Dockerfile-node
    image: app-node
    depends_on:
      - rabbitmq
      - mysql
    env_file: ./env/node.env
    
  node-exporter:
    container_name: node-exporter
    hostname: node-exporter
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: unless-stopped

  docker-exporter:
    container_name: docker-exporter
    hostname: docker-exporter
    image: prometheusnet/docker_exporter:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9417:9417
    restart: always

  mysqld_exporter_high_res:
    image: prom/mysqld-exporter:latest
    container_name: db1_mysqld_exporter_hres
    environment:
      - DATA_SOURCE_NAME=root:@(127.0.0.1:3306)/
    ports:
      - "9104:9104"
    labels:
      - "mon.percona.container_type=collector"
    depends_on:
      - mysql
      
volumes:
  portainer_data: